Feature/integration specs
PNdunguMaina/blog_app pull request #8
Opened 2022-11-16 13:12 UTC by PNdunguMaina

In this project, I did the following: ⚒️ 

- [ ] Wrote integration tests with Capybara gem.
- [ ] Secured app from n+1 problems with Bullet gem.

2022-11-16 14:27 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @PNdunguMaina 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-16 14:27 UTC, tresorsawasawa commented on spec/views/user_spec.rb
> +    end
- [ ] Good job implementing most of the tests required for this view. So, I noticed that you missed one of the [required tests](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/intergration_spec_and_n_1_project.md) to match the expected result. You should also add **test(s) that redirects to the post's show page when you click on a post.** Make sure you add it. But, Good job :+1:. 
![Screenshot from 2022-11-16 15-39-52](https://user-images.githubusercontent.com/83042742/202196013-2d9e9b52-4ed2-42b1-8c65-15030e9eef13.png)

2022-11-16 14:27 UTC, tresorsawasawa commented on spec/views/post_spec.rb
> +      end
- [ ] As required for the project, kindly make sure you also add the below missed required tests for this view to match the expected result:
  - Tests that assert you can see the first comments on a post.
  - Tests that assert you can see a section for pagination if there are more posts than fit on the view.
![Screenshot from 2022-11-16 15-48-06](https://user-images.githubusercontent.com/83042742/202197863-aae3c174-02c9-4692-a16c-7aacbe3a14d3.png)

2022-11-16 14:27 UTC, tresorsawasawa commented on spec/views/post_spec.rb
> +      end
- [ ] As required for the project, kindly make sure you also add the below missed required tests for this view to match the expected result and you can update the test to **display how many likes a post has** as it **is repeated twice**
  - Test(s) that asserts you can see the username of each **commentor**.
  - Test(s) that asserts you can see the comment each **commentor left**.
  
![Screenshot from 2022-11-16 15-59-41](https://user-images.githubusercontent.com/83042742/202200474-0f83dbca-4a82-40a8-a7d1-d257c580d115.png)

2022-11-16 14:27 UTC, tresorsawasawa commented on spec/examples.txt
> +./spec/views/user_spec.rb[1:2:7]     | unknown |                        |
- [ ] Kindly make sure all tests for your **views** are **passing**. When trying on my side no one of them has passed and if you can check for the result above no test for views has passed.
Below is the result I get from your views tests(i.e.: `rspec spec/views `)
![Screenshot from 2022-11-16 16-11-13](https://user-images.githubusercontent.com/83042742/202206677-5de2a2d6-fa8b-477a-8182-aec6ba8d7c26.png)

2022-11-18 07:09 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-18 07:33 UTC, merged